export const HEADER = 'header';
export const SIDEBAR = 'sidebar';
export const FOOTER = 'footer';
export const LOGINPAGE = 'loginpage';

//Products
export const SAVE_PRODUCT_GENERAL = 'SAVE_PRODUCT_GENERAL'; 
export const GET_LAST_PRODUCT_ID = 'GET_LAST_PRODUCT_ID'; 

export const SAVE_PRODUCT_PRICE = 'SAVE_PRODUCT_PRICE'; 

export const SAVE_PRODUCT_INVENTORY='SAVE_PRODUCT_INVENTORY';

export const SAVE_PRODUCT_SEO='SAVE_PRODUCT_SEO';

export const SAVE_PRODUCT_ATTRIBUTE='SAVE_PRODUCT_ATTRIBUTE';

export const SAVE_PRODUCT_OPTIONS='SAVE_PRODUCT_OPTIONS';

export const SAVE_PRODUCT_ADDITIONAL='SAVE_PRODUCT_ADDITIONAL';

export const SAVE_PRODUCT_CATAGORIES_GENERAL='SAVE_PRODUCT_CATAGORIES_GENERAL';

export const SAVE_COUPON_GENERAL='SAVE_COUPON_GENERAL';
 
export const SAVE_COUPON_RESTRICTIONS='SAVE_COUPON_RESTRICTIONS';

export const SAVE_COUPON_LIMITS='SAVE_COUPON_LIMITS';

export const SAVE_PAGES ='SAVE_PAGES';

export const SAVE_PAGES_SEO ='SAVE_PAGES_SEO';

export const SAVE_CURRENCY ='SAVE_CURRENCY';

export const SAVE_SETTINGS ='SAVE_SETTINGS';

export const SAVE_MAINTENANCE ='SAVE_MAINTENANCE';

export const SAVE_STORE ='SAVE_STORE';

export const SAVE_SETTINGS_MAIL ='SAVE_SETTINGS_MAIL';

export const SAVE_SETTINGS_NEWSLETTER ='SAVE_SETTINGS_NEWSLETTER';

export const SAVE_SETTINGS_CUSTOM_CSSJS ='SAVE_SETTINGS_CUSTOM_CSSJS';

export const SAVE_FREE_SHIPPING ='SAVE_FREE_SHIPPING';

export const SAVE_LOCAL_PICKUP ='SAVE_LOCAL_PICKUP';

export const SAVE_FLATE_RATE ='SAVE_FLATE_RATE';

export const SAVE_PAY_PAL ='SAVE_PAY_PAL';

export const SAVE_STRIPE ='SAVE_STRIPE';

export const SAVE_RAZOR_PAY ='SAVE_RAZOR_PAY';

export const SAVE_INSTA_MOJO ='SAVE_INSTA_MOJO';

export const SAVE_CASH_ON_DELIVERY ='SAVE_CASH_ON_DELIVERY';

export const SAVE_BANK_TRANSFER ='SAVE_BANK_TRANSFER';

export const SAVE_MONEY_ORDER ='SAVE_MONEY_ORDER';

export const SAVE_USER_ACCOUNT ='SAVE_USER_ACCOUNT';

export const SAVE_USER_ROLE ='SAVE_USER_ROLE';

export const SAVE_STORE_FRONT_GENERAL ='SAVE_STORE_FRONT_GENERAL';

export const SAVE_STORE_FRONT_MENU ='SAVE_STORE_FRONT_MENU';

export const SAVE_STORE_FRONT_FEATURES ='SAVE_STORE_FRONT_FEATURES';

export const SAVE_STORE_FRONT_SOCIAL_LINKS ='SAVE_STORE_FRONT_SOCIAL_LINKS';

export const SAVE_STORE_FRONT_FEATURE_CATEGORIES ='SAVE_STORE_FRONT_FEATURE_CATEGORIES';

export const SAVE_STORE_FRONT_PRODUCT_TAB_ONE ='SAVE_STORE_FRONT_PRODUCT_TAB_ONE';

export const SAVE_STORE_FRONT_TOP_BRANDS ='SAVE_STORE_FRONT_TOP_BRANDS';

export const SAVE_FLASH_SALE_VERTICAL_PRODUCTS ='SAVE_FLASH_SALE_VERTICAL_PRODUCTS';

export const SAVE_PRODUCT_GRID ='SAVE_PRODUCT_GRID';

export const SAVE_PRODUCT_TAB_TWO ='SAVE_PRODUCT_TAB_TWO';